Clarifications of did:tdw features (abstract) and definitions
bcgov/trustdidweb pull request #84
Opened 2024-07-31 18:41 UTC by martipos

references added, in the abstract and the definitions

SCID benefits summarized and description on portability added and separated from it, both in abstract

update of definitions for DID Log and Log Entries, and added definition for did:web

2024-07-31 22:17 UTC, swcurran commented on spec/abstract.md
> +- A [[def: self-certifying identifier]] (SCID) for the DID. The SCID, globally unique and
This “def” should be a “ref” — my mistake.

2024-07-31 22:18 UTC, swcurran commented on spec/abstract.md
> +  embedded in the DID, is derived from the initial [[ref: DIDDoc]]. It ensures the integrity
Should be: “is derived from the initial [[ref: DID log entry]].”

2024-07-31 22:20 UTC, swcurran commented on spec/definitions.md
> +[[def: Entry, Entries, DID [[ref: Log Entry]], [[ref: DID Log]] Entries]]
Arrgghh…those “refs” sneaking into the defs.  I’ll fix my “semi-automatic” tool to not do that in the future.  In the mean time, please remove the “ref” links in the “def” line.  Again — my mistake.

2024-07-31 22:20 UTC, swcurran commented on spec/definitions.md
>  [[def: DID:web]]
Should be lower case “DID” — my bad.

2024-07-31 22:21 UTC, swcurran requested changes
Looks good — a few tweaks, mostly from things that I had wrong in the first place. What about also adding your name to the editors list?

2024-08-01 13:09 UTC, martipos commented on spec/abstract.md
> +  embedded in the DID, is derived from the initial [[ref: DIDDoc]]. It ensures the integrity
uu, this was a nasty one.

2024-08-01 13:12 UTC, martipos commented on spec/definitions.md
>  [[def: DID:web]]
```suggestion
[[def: did:web]]
```

2024-08-01 14:25 UTC, martipos commented
messed up the DCO as the names used on github and locally seam not to be the same - thought they would be synced. my mistake. Will therefore close this PR and create a new one with the review comments addressed.

2024-08-01 14:25 UTC, closed without merging