Clarification of DID creation (registration)
bcgov/trustdidweb pull request #88
Opened 2024-08-07 15:55 UTC by martipos

Consolidated information where it made sense, deleted redundant information and referenced to complementary information in the specification.

Signed-off-by: martipos <176692840+martipos@users.noreply.github.com>

2024-08-09 16:01 UTC, swcurran commented on spec/specification.md
> +   The [[ref: DID log entriy]] is an input JSON array that when completed contains the following items:
Typo: “entriy"

2024-08-09 16:02 UTC, swcurran commented on spec/specification.md
> +   1. Note: The placeholders (the string `{SCID}`) **MUST** be in every place in the [[ref: DIDDoc]] where
Singular “placeholder” in this spot.

2024-08-09 17:25 UTC, swcurran commented on spec/specification.md
> +   `did:tdw:{SCID}:example.com:dids:issuer#key-1`, etc.). For the rest of the [[ref: DIDDoc]]
How about for the last line — “The [[ref: DIDDoc]] can contain any other content as deemed necessary by the [[ref: DID Controller]]."

2024-08-09 17:27 UTC, swcurran requested changes
Looks great. Just a couple of tweaks proposed and a typo to fix.

2024-08-10 08:49 UTC, martipos reviewed
Added inputs by @swcurran 
Signed-off-by: martipos <176692840+martipos@users.noreply.github.com>

2024-08-10 08:49 UTC, martipos commented on spec/specification.md
> +   `did:tdw:{SCID}:example.com:dids:issuer#key-1`, etc.). For the rest of the [[ref: DIDDoc]]
```suggestion
   `did:tdw:{SCID}:example.com:dids:issuer#key-1`, etc.). The [[ref: DIDDoc]] can contain any other content as deemed necessary by the [[ref: DID Controller]].
```

2024-08-10 08:49 UTC, martipos commented on spec/specification.md
> +   whatever content can be added as required.
```suggestion
 ```

2024-08-10 08:49 UTC, martipos commented on spec/specification.md
> +   1. Note: The placeholders (the string `{SCID}`) **MUST** be in every place in the [[ref: DIDDoc]] where
```suggestion
   1. Note: The placeholder (the string `{SCID}`) **MUST** be in every place in the [[ref: DIDDoc]] where
```

2024-08-10 08:49 UTC, martipos commented on spec/specification.md
> +   The [[ref: DID log entriy]] is an input JSON array that when completed contains the following items:
```suggestion
   The [[ref: DID log entry]] is an input JSON array that when completed contains the following items:
```

2024-08-10 08:53 UTC, martipos commented
thank you @swcurran for you inputs ! :-)

2024-08-12 16:11 UTC, swcurran approved these changes

2024-08-12 16:11 UTC, merged